spring.application.name=locationlens

# Debugging
logging.level.org.springframework.security=TRACE

spring.security.oauth2.client.provider.keycloak.issuer-uri=${IDP_URI}
spring.security.oauth2.client.registration.common-idp.provider=keycloak
spring.security.oauth2.client.registration.common-idp.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.common-idp.client-id=${IDP_CLIENT_ID}
spring.security.oauth2.client.registration.common-idp.client-secret=${IDP_CLIENT_SECRET}
spring.security.oauth2.client.registration.common-idp.scope=openid
